### ISSUE TITLE
nlpdict.com temporary or permanent down?

### ISSUE THREAD

**Issue by ghost** [AnkiUniversal/NLP-Japanese-Dictionary#1]
Hello,

I just wanted to visit nlpdict.com, which seems to be not working.
Is it temporary or permanently down?

**Comment by AnkiUniversal** [comment]
Hi,
 Our current official website is now located at: https://nlpjapanesedictionary.wordpress.com/
 I though we had already changed all our addresses to the new website. Could you tell us where you found nlpdict.com?

**Comment by ghost** [comment]
Hi,

looks like the listing in the Microsoft Store (NPL Japanese Dictionary Website) is still pointing to nlpdict.com.

**Comment by AnkiUniversal** [comment]
Hi,

 Thank you for informing us about this. We'll update the listing on Microsoft Store soon.

**Comment by ghost** [comment]
You are welcome.
